### ISSUE TITLE
[Bug] Sometimes fail to render Chinese character

### ISSUE THREAD

**Issue by zhiyuan-251** [Chaitanya-Shahare/lazygit-for-vscode#1]
**Description**

When I open the terminal as a Tab in vscode, the chinese characters are not rendered at first.  When I use key or mouse to click the place where the character is, the chinese appears.

**Environment**

* OS : Win11
* VSCode Version: 1.80.2
* Plugin Version: 1.0.0
  
**bug details (for visual)**

* The expected visual in Powershell 
![image](https://github.com/Chaitanya-Shahare/lazygi-for-vscode/assets/78415497/8b89c9e2-767b-47e3-b968-9856e8b74176)

* The visual in VSCode
![image](https://github.com/Chaitanya-Shahare/lazygi-for-vscode/assets/78415497/53ef4de2-aaff-40e6-a5ec-f58cf2329150)

After use `[]` to switch branches, the ;the characters are, however, the same color with background without key/mouse operations.

![image](https://github.com/Chaitanya-Shahare/lazygi-for-vscode/assets/78415497/be700ae8-fed4-4c85-a813-742d547b24e9)

**The suggestion/idea to fix it**

* Maybe this is an issue of Powershell in VSCode or LazyGit? I feel not sure

**Other Information**

Thank you for development though :) And i like your extension

**Comment by Chaitanya-Shahare** [comment]
Thanks for the feedback and the issue I'll look into it.

**Comment by balwaniankit** [comment]
This issue is of Lazygit as they've just added the 'zh' code in the language and not 'zh-CN'. Due to this, the Chinese characters are not being rendered at first.
You can refer this PR of lazygit : [https://github.com/jesseduffield/lazygit/pull/2842#issue-1827307899](url)

**Comment by zhiyuan-251** [comment]
> This issue is of Lazygit as they've just added the 'zh' code in the language and not 'zh-CN'. Due to this, the Chinese characters are not being rendered at first. You can refer this PR of lazygit : [https://github.com/jesseduffield/lazygit/pull/2842#issue-1827307899](url)

Thank you for your help! I know where the bug is now and it helps me use your extension better.
