### ISSUE TITLE
Exiting on powershell

### ISSUE THREAD

**Issue by sadan4** [Chaitanya-Shahare/lazygit-for-vscode#15]
`lazygit && exit` does not work in Powershell. it runs lazygit but does not exit after

`lazygit; exit` does work, but I wasn't able to find a place to set a custom command

**Comment by Chaitanya-Shahare** [comment]
Thank you for raising the issue I'll try to add a field to add a custom command in the settings for the extension by this weekend.

**Comment by Chaitanya-Shahare** [comment]
Sorry for the delay. I hope this fixes your issue. You can test it out.

**Comment by sadan4** [comment]
Thanks so much. I'll test it the next time I use windows
