### ISSUE TITLE
Different behaviours using VSCode nvim

### ISSUE THREAD

**Issue by FulecoRafa** [Chaitanya-Shahare/lazygit-for-vscode#2]
I'm using vscode vim for my workflow and I set the following command:
```json
"vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": [
                " ",
                "g",
                "g"
            ],
            "commands": [
                "lazygit.openLazygit"
            ]
        },
]
```
This opens my terminal tray at the bottom and opens lazygit in it

However, using the command itself (through ctrl+shift+p) results in vscode opening a new editor with a terminal in it with lazygit

Finally, when I'm done with lazygit, The terminal stays open, it just quits lazyvim

## Expected behaviour
Always open in a new tab or, at least, open in a similar fashion

### Add a behaviour configuration
This decides how to open lazygit
- `tab`: always open lazygit in a new tab terminal
- ` automatic`: use the existing tray terminal if it exists, use a tab otherwise
- `tray`: use the existing tray terminal, create a tray terminal otherwise

### Exit terminal alongside lazygit
Add a `&& exit` to the terminal so it exists and closes the terminal if it's a tab

**Comment by FulecoRafa** [comment]
Just a quick comment, I would love to this myself should you agree with the proposal

**Comment by Chaitanya-Shahare** [comment]
You can work on it! Looking forward to this feature.

**Comment by Chaitanya-Shahare** [comment]
this is fixed please check it out

**Comment by FulecoRafa** [comment]
Wow I took a long time to actually come back to this. Will definetly check it out
