### ISSUE TITLE
[BUG] lazygit autostashes all changes

### ISSUE THREAD

**Issue by FulecoRafa** [Chaitanya-Shahare/lazygit-for-vscode#6]
Didn't notice anything specially weird, but lazygit keeps stashing my change when I use `lazygit.openLazygit`

**Comment by Chaitanya-Shahare** [comment]
Can you provide the steps to reproduce this bug?

**Comment by ghost** [comment]
I have a (probably) similar error. If VSCode tries to enable a Python Virtual Environment on Terminal start it would automatically type something like `source path/to/venv`. The beginning of this string goes to lazygit already. Which then `s`tashes.

**Comment by dnlbauer** [comment]
I have the same issue. When I open lazygit, it starts stashing and pre-inserts the `source ...` line.

<img width="873" height="203" alt="Image" src="https://github.com/user-attachments/assets/6e785bc0-ef23-4ff4-816f-571567548f47" />
