### ISSUE TITLE
[BUG] Terminal does not move to editor consistently in WSL

### ISSUE THREAD

**Issue by zolrath** [Chaitanya-Shahare/lazygit-for-vscode#7]
Hello! Love the plugin, definitely prefer lazygit to the inbuild VSCode git setup.

When I'm working on a project in Windows, everything works great, however once I start working on a project in WSL things get a bit odd. The "workbench.action.terminal.moveToEditor" command doesn't seem to actually be triggering which leads to my terminal being opened in the bottom of my screen and my editor being focused.

For now, I can manually hit my hotkey to focus the terminal and use lazygit but it's not ideal.

Thanks for this making this wrapper!

**Comment by Chaitanya-Shahare** [comment]
I'm glad you are enjoying the extension. 

I haven't tested the plugin for windows, I'll look into it and try to fix it.

**Comment by Chaitanya-Shahare** [comment]
I ran some tests on Windows with WSL (Ubuntu) set as the default terminal, and everything seemed to be working as expected on my end. Just to clarify, were you also using the WSL terminal as your default terminal when encountering the problem?

**Comment by zolrath** [comment]
Yep!
WSL terminal is my default terminal.

For the exact behavior:
1. Launch VS Code
2. Trigger `lazygit.openLazygit`. This seems to open a full screen terminal, but isn't launching lazygit.
![image](https://github.com/Chaitanya-Shahare/lazygit-for-vscode/assets/454563/0c039832-74f6-48ad-87af-3cd27157dfe4)

3. Close that terminal, run the command again. This time it opens a new smaller terminal, but the cursor is still focused on the file I'm editing, not the terminal.
![image](https://github.com/Chaitanya-Shahare/lazygit-for-vscode/assets/454563/7d5c1b59-df2d-417f-9c97-6cb712dd1541)

I've tried with both fish and bash as my default shells and there was no difference between the two.

**Comment by hongkiulam** [comment]
I recently moved from Mac to Windows and I am experiencing this as well
